$('.games').hover(function(){$(this).children('.hover-box').show(100)},function(){$(this).children('.hover-box').hide(100)})
if($('div').hasClass('swiper-container')){var swiper=new Swiper('.swiper-container',{cssMode:true,navigation:{nextEl:'.swiper-button-next',prevEl:'.swiper-button-prev',},pagination:{el:'.swiper-pagination'},mousewheel:true,keyboard:true,parallax:true,autoplay:{delay:3000,},speed:800,autoplayDisableOnInteraction:false});}
function login()
{$('.sign-in-modal').addClass('active');$('.inner--sign-in-modal').addClass('active');setTimeout(function(){$('.overlay').removeClass('sign-up-side');$('.overlay').addClass('sign-in-side');$('.tab-sign-up').removeClass('active');$('.tab-sign-in').addClass('active');$('.content-sign-up').removeClass('active');$('.content-sign-in').addClass('active');},400);}
$('.user-photo li:nth-child(3)').click(function(){$('.user-hover').toggleClass('d-block')});$('.sign-in-modal').click(function(){$('.sign-in-modal').removeClass('active');$('.inner--sign-in-modal').removeClass('active');});$('.inner--sign-in-modal').click(function(e){e.stopPropagation();})
$('.close-login').click(function(){$('.sign-in-modal').removeClass('active');$('.inner--sign-in-modal').removeClass('active');})
$('.modal-sign').click(function(){$('.sign-in-modal').addClass('active');$('.inner--sign-in-modal').addClass('active');setTimeout(function(){$('.overlay').removeClass('sign-up-side');$('.overlay').addClass('sign-in-side');$('.tab-sign-up').removeClass('active');$('.tab-sign-in').addClass('active');$('.content-sign-up').removeClass('active');$('.content-sign-in').addClass('active');},400);return false;});$('.inner--sign-in-modal .close-modal').click(function(){$('.sign-in-modal').removeClass('active');$('.inner--sign-in-modal').removeClass('active');});$('.val-info .tab').click(function(){if($(this).hasClass('tab-sign-in')==true){$('.overlay').removeClass('sign-up-side');$('.overlay').addClass('sign-in-side');$('.tab-sign-up').removeClass('active');$('.tab-sign-in').addClass('active');$('.content-sign-up').removeClass('active');$('.content-sign-in').addClass('active');}else{$('.overlay').removeClass('sign-in-side');$('.overlay').addClass('sign-up-side');$('.tab-sign-in').removeClass('active');$('.tab-sign-up').addClass('active');$('.content-sign-in').removeClass('active');$('.content-sign-up').addClass('active');}});$('.input-firstname').keyup(function(){var getText=$(this).val();console.log(getText);$('.greetings-name').html(getText);});$('.input-lastname').keyup(function(){var getText=$(this).val();console.log(getText);$('.greetings-surname').html(getText);});$('.modal-sign2').click(function(){$('.sign-in-modal').addClass('active');$('.inner--sign-in-modal').addClass('active');setTimeout(function(){$('.overlay').removeClass('sign-in-side');$('.overlay').addClass('sign-up-side');$('.tab-sign-in').removeClass('active');$('.tab-sign-up').addClass('active');$('.content-sign-in').removeClass('active');$('.content-sign-up').addClass('active');},400);});$('.val-info .tab').click(function(){if($(this).hasClass('tab-sign-up')==true){$('.overlay').removeClass('sign-in-side');$('.overlay').addClass('sign-up-side');$('.tab-sign-in').removeClass('active');$('.tab-sign-up').addClass('active');$('.content-sign-in').removeClass('active');$('.content-sign-up').addClass('active');}else{$('.overlay').removeClass('sign-up-side');$('.overlay').addClass('sign-in-side');$('.tab-sign-up').removeClass('active');$('.tab-sign-in').addClass('active');$('.content-sign-up').removeClass('active');$('.content-sign-in').addClass('active');}});$('.about .card-header').on('click',function(){$(this).children('.btn-block i').toggleClass('rot')})
$('.panel-collapse').on('show.bs.collapse',function(){$(this).siblings('.panel-heading').addClass('active');});$('.panel-collapse').on('hide.bs.collapse',function(){$(this).siblings('.panel-heading').removeClass('active');});$('.faq li').click(function(){$(this).children('.faq-content').toggle(300);$(this).toggleClass('actives')});$('.faq li:first-child').click(function(){$(this).toggleClass('actives1')});$('.faq li:last-child').click(function(){$(this).children('.faq-content').css('border-bottom','1px solid gainsboro')});$('.mobile-menu-box-left ul li').click(function(){$(this).find('i').toggleClass('circle')
$(this).children('.sub-menus').toggleClass('d-block')});$('.mobile-menu-left').click(function(){$('.mobile-menu-box-left').addClass('open-it')
$('.mobile-menu-box-right').removeClass('open-it-right')
$('.mobile-menu-box-left').removeClass('close-it')});$('.menu-close').click(function(){$('.mobile-menu-box-left').addClass('close-it')
$('.mobile-menu-box-left').removeClass('open-it')});$('.mobile-menu-right').click(function(){$('.mobile-menu-box-left').removeClass('open-it')
$('.mobile-menu-box-right').addClass('open-it-right')
$('.mobile-menu-box-right').removeClass('close-it-right')})
$('.menu-close-right').click(function(){$('.mobile-menu-box-right').addClass('close-it-right')
$('.mobile-menu-box-right').removeClass('open-it-right')});